version: "3.11"
services:
  postgres_app:
    image: postgres:alpine
#    container_name: ${POSTGRES_HOST}
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    env_file:
      - .env
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  redis_app:
    image: bitnami/redis:latest
#    container_name: ${REDIS_HOST}
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
