# Generated by Django 5.0.6 on 2024-06-25 17:09

import django.db.models.deletion
import mails.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mails", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MailFiles",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to=mails.models.file_directory_path)),
                (
                    "mail",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="mails.mail",
                    ),
                ),
            ],
        ),
    ]
