# Generated by Django 5.0.6 on 2024-06-25 17:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mails", "0002_mailfiles"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mail",
            name="received_date",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="mail",
            name="sent_date",
            field=models.DateTimeField(null=True),
        ),
    ]
