# Generated by Django 5.0.6 on 2024-06-25 06:37

import domain.enums.emails
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=319, unique=True)),
                ("password", models.CharField(max_length=50)),
                (
                    "email_type",
                    models.CharField(
                        choices=[
                            (domain.enums.emails.EmailType["GMAIL"], "gmail"),
                            (domain.enums.emails.EmailType["YANDEX"], "yandex"),
                            (domain.enums.emails.EmailType["MAIL"], "mail"),
                        ],
                        max_length=6,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="EmailMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject", models.CharField(max_length=100)),
                ("sent_date", models.DateTimeField()),
                ("received_date", models.DateTimeField()),
                ("text", models.TextField(max_length=1000, null=True)),
            ],
        ),
    ]
